# Generated by Django 2.0.7 on 2019-05-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axfuser',
            name='u_email',
            field=models.CharField(max_length=64),
        ),
    ]
